---
driver:
  name: docker
platforms:
  - name: debian13
    image: geerlingguy/docker-debian13-ansible
    volumes:
      - /var/lib/containerd
    command: ""
    pre_build_image: true
    cgroupns: host
provisioner:
  name: ansible
  ansible_args:
    - --diff
lint: |
  set -e
  yamllint .
  ansible-lint .
