#! /bin/bash
#
# wrapper script to use the nagios plugin mode of needrestart
# as a check_mk local check (see: https://mathias-kettner.de/checkmk_localchecks.html)
#

declare -r OFILE=/tmp/.needrestart.out

which sudo >/dev/null 2>&1
if [ $? -eq 0 ]; then
	sudo -n -- /usr/sbin/needrestart -p > $OFILE 2>/dev/null
else
	/usr/sbin/needrestart -p > $OFILE 2>/dev/null
fi

declare -ri STATUSERR=$?

STATUSERRTXT="OK"
if [ $STATUSERR -eq 1 ]; then
	STATUSERRTXT="WARNING"
elif [ $STATUSERR -gt 1 ]; then
	STATUSERRTXT="CRITICAL"
fi
STATUSDESCR=$(cat $OFILE | sed '1!d; s/^[A-Z]\+ - //g;s/|.*//g')
STATUSPERF=$(cat $OFILE | sed '1!d; s/.*| *//g;s/ /|/g')
if [ $STATUSERR -gt 0 ]; then
	STATUSDESCREXT=$(sed '1d; s/-//g' $OFILE)
	[ -n "$STATUSDESCREXT" ] && STATUSDESCR="$STATUSDESCR (${STATUSDESCREXT//[$'\r\n']})"
fi

echo "$STATUSERR NEEDRESTART $STATUSPERF $STATUSERRTXT - $STATUSDESCR"
exit $STATUSERR
